title: <p align = "center">Sumayya Gazal</p>
logo: /assets/img/sumayya.png
description: 
<p align = "center">
👋 Welcome to my GitHub Portfolio!
I'm Sumayya Gazal, and I'm deeply passionate about machine learning and its incredible potential to revolutionize industries and solve complex problems. With a background in Data Science, I'm dedicated to honing my skills and exploring the fascinating world of machine learning.
**What You'll Find Here:**
- 🤖 Machine Learning Projects: Dive into my journey through various machine learning projects, ranging from image classification to natural language processing.
- 📚 Learning Adventures: Follow along as I document my learning experiences, share insights, and discuss best practices in the machine learning landscape.
- 💡 Collaborations: I'm eager to connect with fellow learners and experts in the field. Let's collaborate on exciting ML endeavors!
**Current Focus:**
I'm currently immersed in learning the intricacies of machine learning, from fundamental algorithms to cutting-edge techniques. Join me as I explore, experiment, and expand my knowledge.
Thank you for visiting my portfolio, and I look forward to sharing the wonders of machine learning with you! 🚀

</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
